#! /usr/bin/env bash


# Get us "modern" regexps with sed.
if [ `uname` == "Linux" ]; then
   sed="sed -r"
else
   sed="sed -E"
fi

# Replace timestamps in UNIX format (number of seconds, with fractional part) with XXXs.
sed 's/[0-9]\{10\}\.[0-9]\{2,8\}/XXXXXXXXXX.XXXXXX/g' | \
# Remove uids
awk '
BEGIN { FS="\t"; OFS="\t"; }
/^[^#]/ {
    if ( column > 0 ) {
        $column = "XXXXXXXXXXX";
    }
}
/^#fields/ {
    for ( i = 2; i <= NF; ++i ) {
        if ( $i == "uid" )
            column = i - 1;
        }
    }
{ print }
' | \
# Remove open/close
$sed 's/^ *#(open|close).(19|20)..-..-..-..-..-..$/#\1 XXXX-XX-XX-XX-XX-XX/g'


